<?php
namespace common\controllers;

use common\services\log\AccessBaseLogic;
use Yii;
/**
 * 接口无需用户登录及权限控制器基类
 */

class ApiCommonContoller extends BaseContoller
{
    public $enableCsrfValidation = false ;
    public $user = null;
    public $userId = 0;

    public function beforeAction($action)
    {
        $this->setUser();
        return true;
    }

    public function afterAction($action, $result)
    {
        $runResult = parent::afterAction($action, $result);
        //根据配置判断是否需要记录访问日志
        $saveAccessLog = Yii::$app->params['save_access_log'] ?? false;
        if($saveAccessLog){
            $accesLog = new AccessBaseLogic();
            $accesLog->save();
           
        }
        return $runResult; // TODO: Change the autogenerated stub
    }


    /**
     * 根据token获取用户
     * @throws \yii\db\Exception
     */
    public function setUser(){

        $token = $this->post('token','');
        if(!empty($token) && strlen($token)<500){
            $this->user = [];
            $this->userId = 10;
            //$this->user = Yii::$app->db->createCommand('select * from {{%user}} where is_delete=0 and token_out_time>:token_out_time and token=:token',[':token'=>$token,':token_out_time'=>date('Y-m-d H:i:s',time())])->queryOne();
        }
    }

    /**
     * 获取当前contoller 用户id
     * @return int
     */
    public function getUserId(){
        return $this->userId;
    }

}
